In [1]:
import numpy as np

In [18]:
a = np.array([[6,4,3],[1,2,8],[5,7,9]]) 
a

array([[6, 4, 3],
       [1, 2, 8],
       [5, 7, 9]])

In [33]:
a[1:3,1:2]

array([[2],
       [7]])

In [5]:
a[:2,:] # get only the first 2 rows

array([[6, 4, 3],
       [1, 2, 8]])

In [6]:
a[:,1:] # get only the  2nd and 3rd col

array([[4, 3],
       [2, 8],
       [7, 9]])

In [9]:
print(a)
a[1:,1:]

[[6 4 3]
 [1 2 8]
 [5 7 9]]


array([[2, 8],
       [7, 9]])

In [14]:
print(a)
np.transpose(a)

[[6 4 3]
 [1 2 8]
 [5 7 9]]


array([[6, 1, 5],
       [4, 2, 7],
       [3, 8, 9]])

In [16]:
# negative indexing
print(a)
a[::-1]

[[6 4 3]
 [1 2 8]
 [5 7 9]]


array([[5, 7, 9],
       [1, 2, 8],
       [6, 4, 3]])

In [35]:
print(a)

a.flatten()

[[6 4 3]
 [1 2 8]
 [5 7 9]]


array([6, 4, 3, 1, 2, 8, 5, 7, 9])

In [37]:
## Stack and vstack
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print("\n")
print('Vertical Append:', np.vstack((f, g)))

('Horizontal Append:', array([1, 2, 3, 4, 5, 6]))


('Vertical Append:', array([[1, 2, 3],
       [4, 5, 6]]))


In [42]:
### Matmul: matruc product of two arrays
h = np.array([[1,2],[3,4]] )
i = np.array([[5,6],[7,8]] )
print(h)
print(i)
### 1*5+2*7 = 19
np.matmul(h, i)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [45]:
##Broadcasting
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
print("Multiplication with broadcasting: ")
print(A)
print(B)
print(A*B)
# print("... and now addition with broadcasting: ")
# print(A + B)

Multiplication with broadcasting: 
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[1 2 3]
[[11 24 39]
 [21 44 69]
 [31 64 99]]
